---
:concurrency: 80
production:
  :concurrency: 80
:timeout: 8
:queues:
  - [sourcerank, 3]
  - [user, 1]
  - [critical, 1]
  - [repo_maintenance_stat_high, 1]
    # - [mailers, 8]
  - [tree, 1]
  - [repo_maintenance_stat, 1]
  - [default, 3]
  - [small, 5]
  - [score, 2]
  - [status, 10]
  - [issues, 2]
  - [owners, 5]
  - [repo, 1]
  - [repo_maintenance_stat_low, 1]
